# 🔥 **Complete NumPy for Data Science README** 🐍

Based on the comprehensive tutorial by Hitesh Choudhary and the extensive data science workflow, here's your ultimate, emoji-rich NumPy README guide for mastering numerical computing in Python!

## 📚 **Table of Contents**

- [🔥 Introduction & Course Overview](#-introduction--course-overview)
- [🎯 Why NumPy is Essential](#-why-numpy-is-essential)
- [🏗️ History & Foundation](#-history--foundation)
- [🚀 Installation & Setup](#-installation--setup)
- [📊 Core Data Structures](#-core-data-structures)
- [🔧 Creating Arrays](#-creating-arrays)
- [🎯 Array Operations](#-array-operations)
- [📈 Mathematical Operations](#-mathematical-operations)
- [🖼️ Image Processing Basics](#-image-processing-basics)
- [⚡ Performance & Optimization](#-performance--optimization)
- [💡 Best Practices](#-best-practices)
- [🎓 Advanced Topics](#-advanced-topics)
- [🔗 Resources & Community](#-resources--community)


## 🔥 **Introduction & Course Overview**

**Welcome to Chai aur NumPy!** ☕ This comprehensive guide is based on Hitesh Choudhary's complete NumPy course, designed to take you from absolute beginner to advanced practitioner in numerical computing with Python.

### 🎯 **What You'll Master:**
- 🏗️ **Foundation**: Complete NumPy basics and array creation methods
- ⚙️ **Operations**: Element-wise operations, broadcasting, and mathematical functions
- 📊 **Real-world Data**: Practice with actual datasets and image processing
- 🖼️ **Image Matrix**: Store images as matrices and convert to dark mode
- 🚀 **Performance**: Understand why NumPy is faster than Python lists

### ✨ **Course Structure:**

| 📖 **Phase** | 📝 **Content** | ⏰ **Duration** |
|--------------|----------------|----------------|
| **Phase 1** | NumPy Foundation & Array Creation | 00:12:34 - 00:46:42 |
| **Phase 2** | Operations on NumPy Arrays | 00:46:42 - 01:27:22 |
| **Phase 3** | Practice with Real-World Data | 01:27:22 - 02:06:08 |
| **Phase 4** | Image Processing & Dark Mode | 02:06:08 - 02:24:03 |


## 🎯 **Why NumPy is Essential**

### 💪 **Data Science Foundation**

NumPy is the **backbone of the entire Python data science ecosystem**. Every major library depends on it:

- 🐼 **Pandas**: Built on top of NumPy arrays
- 🔥 **PyTorch**: Uses NumPy-like tensor operations
- 🧠 **TensorFlow**: Fundamental operations based on NumPy
- 📊 **Matplotlib**: Visualization powered by NumPy arrays
- 🤖 **Scikit-learn**: All algorithms work with NumPy arrays

**Key Advantages:**
- 🏃♂️ **Speed**: 50-100x faster than Python lists
- 💾 **Memory**: Uses less memory due to homogeneous data types
- 🔧 **Functionality**: Rich mathematical and statistical functions
- 🌐 **Integration**: Seamless with other scientific libraries

## 🏗️ **History & Foundation**

### 🎨 **The C++ Foundation**

NumPy's incredible speed comes from its **C++ core**:

```
Python Interface (Easy to use)
        ↓
NumPy Python API
        ↓
C++ Core Implementation (Super fast)
        ↓
Direct CPU/GPU Access
```

### 🧮 **Matrix Operations**

The power of NumPy lies in **matrix mathematics**:

```
Matrix A = [1, 2, 3]    Matrix B = [2, 5, 7]
           [4, 5, 6]               [9, 1, 1]

Addition:  [1+2, 2+5, 3+7] = [3,  7, 10]
           [4+9, 5+1, 6+1]   [13, 6,  7]

Multiplication: Much more complex calculations!
```

**Why This Matters:**
- 🤖 **Machine Learning**: Entire ML foundation is matrix operations
- 🎮 **Computer Graphics**: Image processing, 3D rendering
- 📊 **Data Analysis**: Statistical computations on large datasets
- 🔬 **Scientific Computing**: Physics simulations, engineering calculations


## 🚀 **Installation & Setup**

### 📦 **Installation Methods**

```bash
# 🐍 Using pip (most common)
pip install numpy

# 🍎 macOS users (use pip3)
pip3 install numpy

# 🐍 Using conda (recommended for data science)
conda install numpy

# 🔄 Upgrade existing installation
pip install --upgrade numpy
```

### 💻 **Import and Setup**

```python
# 🌟 Standard import convention
import numpy as np

# 🔍 Check version
print(f"NumPy version: {np.__version__}")

# 📊 Create your first array
my_first_array = np.array([1, 2, 3, 4, 5])
print(f"My first NumPy array: {my_first_array}")
```

### 🛠️ **Development Environment Setup**

**Recommended Tools:**
- 🆚 **VS Code**: Excellent for beginners (as used in tutorial)
- 📓 **Jupyter Notebooks**: Interactive development
- 🐍 **Anaconda**: Complete data science package
- 🖥️ **PyCharm**: Professional IDE with data science features

In [38]:
import numpy as np
import time

## 📊 **Core Data Structures**

### 🔢 **Understanding Dimensions**

NumPy works with different dimensional data structures:

#### 1️⃣ **Vector (1D Array)**

In [39]:
# 🎯 One-dimensional array (Vector)
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector: {vector}")
print(f"Shape: {vector.shape}")  # (5,)
print(f"Dimensions: {vector.ndim}")  # 1

Vector: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1


#### 2️⃣ **Matrix (2D Array)**

In [40]:
# 📋 Two-dimensional array (Matrix)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Matrix:\n{matrix}")
print(f"Shape: {matrix.shape}")  # (2, 3) - 2 rows, 3 columns
print(f"Dimensions: {matrix.ndim}")  # 2

Matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


#### 3️⃣ **Tensor (3D+ Array)**

In [41]:
# 🧊 Three-dimensional array (Tensor)
tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(f"Tensor:\n{tensor}")
print(f"Shape: {tensor.shape}")  # (2, 2, 2)
print(f"Dimensions: {tensor.ndim}")  # 3

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


### 🔄 **List vs NumPy Array**

**Critical Difference:**

In [42]:
# 🐌 Python List Multiplication (Repetition)
python_list = [1, 2, 3]
result = python_list * 2  # [1, 2, 3, 1, 2, 3]
print(f"Python list * 2: {result}")

# ⚡ NumPy Array Multiplication (Element-wise)
numpy_array = np.array([1, 2, 3])
result = numpy_array * 2  # [2, 4, 6]
print(f"NumPy array * 2: {result}")

Python list * 2: [1, 2, 3, 1, 2, 3]
NumPy array * 2: [2 4 6]


## 🔧 **Creating Arrays**

### 📝 **From Python Lists**

In [43]:
# 🎯 Basic array creation
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

# 📊 2D array from nested lists
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"2D Array:\n{arr_2d}")

# ⚠️ Common Mistake to Avoid:
# ❌ Wrong way - passing multiple arrays
# arr_wrong = np.array([1, 2, 3], [4, 5, 6])  # This will error!

# ✅ Correct way - single list containing sublists
arr_correct = np.array([[1, 2, 3], [4, 5, 6]])

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]


### 🏗️ **Built-in Array Creation Functions**

#### 🔢 **Zeros and Ones Arrays**

In [44]:
# 🔘 Array of zeros
zeros_array = np.zeros((3, 4))  # 3 rows, 4 columns of zeros
print("Zeros Array:")
print(zeros_array)

# ⚪ Array of ones
ones_array = np.ones((2, 3))  # 2 rows, 3 columns of ones
print("Ones Array:")
print(ones_array)

# 🎯 Array with custom constant value
sevens_array = np.full((2, 2), 7)  # 2x2 array filled with 7
print("Sevens Array:")
print(sevens_array)

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]
Sevens Array:
[[7 7]
 [7 7]]


#### 🎲 **Random Arrays**

In [45]:
# 🎰 Random values between 0 and 1
random_array = np.random.random((2, 3))
print("Random Array:")
print(random_array)

# 🎯 Random integers in a range
random_ints = np.random.randint(1, 10, size=(3, 3))  # Values from 1-9
print("Random Integers:")
print(random_ints)

# 🎪 Random values from normal distribution
normal_array = np.random.normal(0, 1, (2, 2))  # mean=0, std=1
print("Normal Distribution:")
print(normal_array)

Random Array:
[[0.35288325 0.36286736 0.79581507]
 [0.9829169  0.94880485 0.17212157]]
Random Integers:
[[5 3 1]
 [2 6 3]
 [3 2 7]]
Normal Distribution:
[[ 0.58800263 -0.4920641 ]
 [ 1.38778527  1.54861067]]


#### 🔢 **Sequence Arrays**

In [46]:
# 📈 Range of values (like Python range, but returns array)
range_array = np.arange(0, 10, 2)  # Start=0, Stop=10, Step=2
print(f"Range Array: {range_array}")  # [0, 2, 4, 6, 8]

# 📏 Evenly spaced values
linspace_array = np.linspace(0, 1, 5)  # 5 values from 0 to 1
print(f"Linspace Array: {linspace_array}")  # [0. 0.25 0.5 0.75 1.]

# 🆔 Identity matrix
identity_matrix = np.eye(3)  # 3x3 identity matrix
print("Identity Matrix:")
print(identity_matrix)

Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 🎯 **Array Operations**

### 🔍 **Performance Comparison**

Let's see why NumPy is so much faster:

In [47]:
import time

# 🐌 Python List Performance Test
start_time = time.time()
python_list = list(range(1000000))
result_list = [x * 2 for x in python_list]
list_time = time.time() - start_time

# ⚡ NumPy Array Performance Test
start_time = time.time()
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
numpy_time = time.time() - start_time

print(f"🐌 Python List Time: {list_time:.6f} seconds")
print(f"⚡ NumPy Array Time: {numpy_time:.6f} seconds")
print(f"🚀 NumPy is {list_time / numpy_time:.1f}x faster!")

🐌 Python List Time: 0.098330 seconds
⚡ NumPy Array Time: 0.004694 seconds
🚀 NumPy is 20.9x faster!


**Why NumPy is Faster:**
- 🏠 **Contiguous Memory**: Arrays stored in continuous memory blocks
- 🎯 **Homogeneous Data**: All elements are the same data type
- 🔧 **Vectorized Operations**: Operations applied to entire arrays at once
- 🏎️ **C/C++ Implementation**: Core functions written in compiled languages

### 📊 **Element-wise Operations**

In [48]:
# 🎯 Create sample arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# ➕ Addition
addition = arr1 + arr2
print(f"Addition: {addition}")  # [6, 8, 10, 12]

# ➖ Subtraction
subtraction = arr2 - arr1
print(f"Subtraction: {subtraction}")  # [4, 4, 4, 4]

# ✖️ Multiplication (element-wise)
multiplication = arr1 * arr2
print(f"Element-wise multiplication: {multiplication}")  # [5, 12, 21, 32]

# ➗ Division
division = arr2 / arr1
print(f"Division: {division}")  # [5.0, 3.0, 2.33, 2.0]

# 🔋 Power operation
power = arr1 ** 2
print(f"Square: {power}")  # [1, 4, 9, 16]

Addition: [ 6  8 10 12]
Subtraction: [4 4 4 4]
Element-wise multiplication: [ 5 12 21 32]
Division: [5.         3.         2.33333333 2.        ]
Square: [ 1  4  9 16]


### 📏 **Array Properties**

In [49]:
# 🎯 Sample array for exploration
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("🔍 Array Exploration:")
print(f"Array:\n{sample_array}")
print(f"Shape: {sample_array.shape}")  # (3, 3)
print(f"Size: {sample_array.size}")  # 9 total elements
print(f"Dimensions: {sample_array.ndim}")  # 2 dimensions
print(f"Data type: {sample_array.dtype}")  # int64 (or int32 on some systems)
print(f"Item size: {sample_array.itemsize}")  # 8 bytes per element

🔍 Array Exploration:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Dimensions: 2
Data type: int64
Item size: 8


## 📈 **Mathematical Operations**

### 🔢 **Statistical Functions**

In [50]:
# 📊 Create sample data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("📊 Statistical Analysis:")
print(f"Data: {data}")
print(f"Mean: {np.mean(data)}")  # 5.5
print(f"Median: {np.median(data)}")  # 5.5
print(f"Standard Deviation: {np.std(data)}")  # ~2.87
print(f"Variance: {np.var(data)}")  # ~8.25
print(f"Min: {np.min(data)}")  # 1
print(f"Max: {np.max(data)}")  # 10
print(f"Sum: {np.sum(data)}")  # 55

📊 Statistical Analysis:
Data: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Sum: 55


### 🧮 **Mathematical Functions**

In [51]:
# 📐 Trigonometric functions
angles = np.array([0, np.pi / 4, np.pi / 2, np.pi])
print("📐 Trigonometry:")
print(f"Angles: {angles}")
print(f"Sin: {np.sin(angles)}")
print(f"Cos: {np.cos(angles)}")
print(f"Tan: {np.tan(angles)}")

# 🔢 Exponential and logarithmic
numbers = np.array([1, 2, 3, 4, 5])
print("\n🔢 Exponential & Logarithmic:")
print(f"Numbers: {numbers}")
print(f"Exponential: {np.exp(numbers)}")
print(f"Natural log: {np.log(numbers)}")
print(f"Log base 10: {np.log10(numbers)}")
print(f"Square root: {np.sqrt(numbers)}")

📐 Trigonometry:
Angles: [0.         0.78539816 1.57079633 3.14159265]
Sin: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
Cos: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
Tan: [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]

🔢 Exponential & Logarithmic:
Numbers: [1 2 3 4 5]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log base 10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


### 🎯 **Broadcasting**

Broadcasting allows operations between arrays of different shapes:

In [52]:
# 📊 Broadcasting example
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([10, 20, 30])
vector2 = np.array([[10], [20], [30]])

# 🔥 Broadcasting in action
result = matrix + vector  # Adds vector to each row of matrix
result2 = matrix + vector2

print("🔥 Broadcasting Result:")
print(f"Matrix + Vector:\n{result}")
print(f"Matrix + Vector2:\n{result2}")

# 📈 Scalar broadcasting
scalar_result = matrix * 10  # Multiplies every element by 10
print(f"Matrix * 10:\n{scalar_result}")

🔥 Broadcasting Result:
Matrix + Vector:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
Matrix + Vector2:
[[11 12 13]
 [24 25 26]
 [37 38 39]]
Matrix * 10:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


## 🖼️ **Image Processing Basics**

### 🎨 **Images as Matrices**

Understanding how images are stored as numerical arrays:

In [53]:
# 🖼️ Create a simple "image" (grayscale)
# In real images: 0 = black, 255 = white
simple_image = np.array([
    [0, 50, 100, 150, 200],
    [25, 75, 125, 175, 225],
    [50, 100, 150, 200, 255],
    [75, 125, 175, 225, 200],
    [100, 150, 200, 150, 100]
])

print("🖼️ Simple Grayscale Image Matrix:")
print(simple_image)
print(f"Image shape: {simple_image.shape}")  # (5, 5)

🖼️ Simple Grayscale Image Matrix:
[[  0  50 100 150 200]
 [ 25  75 125 175 225]
 [ 50 100 150 200 255]
 [ 75 125 175 225 200]
 [100 150 200 150 100]]
Image shape: (5, 5)


### 🌙 **Dark Mode Conversion**

Converting images to dark mode (inverting pixel values):

In [54]:
# 🌙 Dark mode conversion (invert grayscale values)
def convert_to_dark_mode(image_array):
    """
    Convert grayscale image to dark mode by inverting values
    Formula: dark_pixel = 255 - original_pixel
    """
    return 255 - image_array


# 🎯 Apply dark mode conversion
dark_image = convert_to_dark_mode(simple_image)

print("\n🌙 Dark Mode Conversion:")
print("Original image:")
print(simple_image)
print("\nDark mode image:")
print(dark_image)

# 📊 Comparison
print(f"\nOriginal range: {simple_image.min()} to {simple_image.max()}")
print(f"Dark mode range: {dark_image.min()} to {dark_image.max()}")


🌙 Dark Mode Conversion:
Original image:
[[  0  50 100 150 200]
 [ 25  75 125 175 225]
 [ 50 100 150 200 255]
 [ 75 125 175 225 200]
 [100 150 200 150 100]]

Dark mode image:
[[255 205 155 105  55]
 [230 180 130  80  30]
 [205 155 105  55   0]
 [180 130  80  30  55]
 [155 105  55 105 155]]

Original range: 0 to 255
Dark mode range: 0 to 255


### 🎨 **Color Images (RGB)**

Working with color images represented as 3D arrays:

In [55]:
# 🌈 Create a simple color image (RGB)
# Shape: (height, width, channels) where channels = [R, G, B]
color_image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],  # Red, Green, Blue pixels
    [[255, 255, 0], [255, 0, 255], [0, 255, 255]],  # Yellow, Magenta, Cyan pixels
    [[128, 128, 128], [64, 64, 64], [192, 192, 192]]  # Gray shades
])

print("🌈 Color Image Shape:", color_image.shape)  # (3, 3, 3)
print("RGB values for first pixel:", color_image[0, 0])  # [255, 0, 0] = Red

# 🎨 Extract individual color channels
red_channel = color_image[:, :, 0]
green_channel = color_image[:, :, 1]
blue_channel = color_image[:, :, 2]

print("\n📊 Color Channels:")
print(f"Red channel:\n{red_channel}")
print(f"Green channel:\n{green_channel}")
print(f"Blue channel:\n{blue_channel}")

🌈 Color Image Shape: (3, 3, 3)
RGB values for first pixel: [255   0   0]

📊 Color Channels:
Red channel:
[[255   0   0]
 [255 255   0]
 [128  64 192]]
Green channel:
[[  0 255   0]
 [255   0 255]
 [128  64 192]]
Blue channel:
[[  0   0 255]
 [  0 255 255]
 [128  64 192]]


## ⚡ **Performance & Optimization**

### 🔬 **Memory Usage Analysis**

In [56]:
import sys

# 📊 Compare memory usage
python_list = [1, 2, 3, 4, 5] * 100000  # 500,000 integers
numpy_array = np.array(python_list)

list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list)
array_memory = numpy_array.nbytes

print("💾 Memory Usage Comparison:")
print(f"Python List: {list_memory:,} bytes")
print(f"NumPy Array: {array_memory:,} bytes")
print(f"Memory Saved: {((list_memory - array_memory) / list_memory) * 100:.1f}%")

💾 Memory Usage Comparison:
Python List: 18,000,056 bytes
NumPy Array: 4,000,000 bytes
Memory Saved: 77.8%


### 🚀 **Vectorization Benefits**

In [57]:
# 🏃‍♂️ Vectorized vs Loop comparison
def slow_operation(arr):
    """Slow: Using Python loop"""
    result = []
    for x in arr:
        result.append(x ** 2 + 2 * x + 1)
    return result


def fast_operation(arr):
    """Fast: Using NumPy vectorization"""
    return arr ** 2 + 2 * arr + 1


# 📊 Performance test
large_array = np.arange(1000000)
large_list = large_array.tolist()

# ⏱️ Time the operations
import time

# Slow method
start = time.time()
slow_result = slow_operation(large_list)
slow_time = time.time() - start

# Fast method
start = time.time()
fast_result = fast_operation(large_array)
fast_time = time.time() - start

print("🚀 Vectorization Performance:")
print(f"Loop method: {slow_time:.4f} seconds")
print(f"Vectorized method: {fast_time:.6f} seconds")
print(f"Speedup: {slow_time / fast_time:.1f}x faster!")

🚀 Vectorization Performance:
Loop method: 0.1764 seconds
Vectorized method: 0.014723 seconds
Speedup: 12.0x faster!


## 💡 **Best Practices**

### ✅ **Do's**

1. **🏷️ Use Standard Import Convention**
   ```python
   import numpy as np  # Always use 'np' alias
   ```

2. **🎯 Choose Appropriate Data Types**
   ```python
   # For integers
   int_array = np.array([1, 2, 3], dtype=np.int32)

   # For floating point
   float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)

   # For booleans
   bool_array = np.array([True, False, True], dtype=bool)
   ```

3. **🔄 Use Vectorized Operations**
   ```python
   # ✅ Good: Vectorized
   result = array1 + array2

   # ❌ Bad: Manual loop
   result = [a + b for a, b in zip(array1, array2)]
   ```

4. **💾 Preallocate Arrays When Possible**
   ```python
   # ✅ Good: Preallocate
   result = np.zeros((1000, 1000))
   for i in range(1000):
       result[i] = some_calculation()

   # ❌ Bad: Growing arrays
   result = []
   for i in range(1000):
       result.append(some_calculation())
   result = np.array(result)
   ```

### ❌ **Don'ts**

1. **🚫 Don't Mix Different Data Types Unnecessarily**
   ```python
   # ❌ Bad: Mixed types force object dtype
   mixed_array = np.array([1, 2.5, 'hello'])  # dtype=object (slow!)

   # ✅ Good: Homogeneous types
   numeric_array = np.array([1, 2, 3])  # dtype=int64 (fast!)
   ```

2. **🚫 Don't Use Loops for Array Operations**
   ```python
   # ❌ Bad: Manual loops
   for i in range(len(array)):
       array[i] = array[i] ** 2

   # ✅ Good: Vectorized
   array = array ** 2
   ```

3. **🚫 Don't Ignore Memory Layout**
   ```python
   # 🎯 For better performance, consider array ordering
   # C-order (row-major) vs F-order (column-major)
   c_array = np.array([[1, 2], [3, 4]], order='C')  # Default
   f_array = np.array([[1, 2], [3, 4]], order='F')  # Fortran-style
   ```


## 🎓 **Advanced Topics**

### 🔍 **Advanced Indexing**

```python
# 🎯 Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Find elements greater than 5
mask = arr > 5
filtered = arr[mask]
print(f"Elements > 5: {filtered}")  # [6, 7, 8, 9, 10]

# 🎪 Fancy indexing
indices = np.array([0, 2, 4, 6])
selected = arr[indices]
print(f"Selected elements: {selected}")  # [1, 3, 5, 7]
```

### 🔄 **Array Reshaping**

```python
# 📐 Reshape operations
original = np.arange(12)
print(f"Original: {original}")  # [0, 1, 2, ..., 11]

# Reshape to different dimensions
matrix_2x6 = original.reshape(2, 6)
matrix_3x4 = original.reshape(3, 4)
matrix_2x2x3 = original.reshape(2, 2, 3)

print(f"2x6 matrix:\n{matrix_2x6}")
print(f"3x4 matrix:\n{matrix_3x4}")
print(f"2x2x3 tensor:\n{matrix_2x2x3}")

# 📏 Automatic dimension calculation
auto_reshape = original.reshape(-1, 4)  # -1 means "calculate automatically"
print(f"Auto reshape (-1, 4):\n{auto_reshape}")  # 3x4 matrix
```

### 🔗 **Array Concatenation**

```python
# 🔗 Joining arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertical stacking (along rows)
v_stack = np.vstack([arr1, arr2])
print(f"Vertical stack:\n{v_stack}")

# Horizontal stacking (along columns)
h_stack = np.hstack([arr1, arr2])
print(f"Horizontal stack:\n{h_stack}")

# General concatenation
concat_0 = np.concatenate([arr1, arr2], axis=0)  # Along rows
concat_1 = np.concatenate([arr1, arr2], axis=1)  # Along columns
```
